### ISSUE TITLE
UI V2 Develop

### ISSUE THREAD

**Issue by bianyunjian** [web3go-xyz/web3go.xyz#101]
dev preview:   
http://16.163.5.216:8088/#/home

**Comment by bianyunjian** [comment]
- [ ] 底部的地址链接 有一些需要更新 @zhanggoodzhi  @LeonITMCuiP @kkkkkguo

**Comment by bianyunjian** [comment]
- [ ]  顶部的导航 目前还未生效, 需要链接到页面对应位置

**Comment by LeonITMCuiP** [comment]
<img width="229" alt="1655093809748" src="https://user-images.githubusercontent.com/97211839/173278672-ff4aeb78-ff80-4140-8aa9-4bbc525492e8.png">
develop 改成development

**Comment by LeonITMCuiP** [comment]
<img width="286" alt="1655094206023" src="https://user-images.githubusercontent.com/97211839/173279286-079a724d-1837-40a7-9450-d7ea6af3812e.png">
我调整后是这样：
Web3Go is an all-in-one open data analytics and service platform where everyone can grasp the value behind blockchain data.

<img width="666" alt="1655094615567" src="https://user-images.githubusercontent.com/97211839/173279978-dd488041-d0cc-4b02-bf69-b2cd4ff3e092.png">
描述的那一句话 最后的.句号可以删掉  另外每一个的描述的这个调大一点？ 还有那个explore也可以大一点 不够醒目

**Comment by LeonITMCuiP** [comment]
<img width="681" alt="1655094904216" src="https://user-images.githubusercontent.com/97211839/173280557-5cf7b3b4-7c15-4447-bd2e-58bf019e9495.png">
这里之前说y有个动态，鼠标放到三个图标处的时候会有放大的动效。  现在还没有。 另外这红框内的字是不是要稍微大一点 然后往右边稍微挪一点。

**Comment by LeonITMCuiP** [comment]
<img width="414" alt="1655095156237" src="https://user-images.githubusercontent.com/97211839/173280816-1ba69626-0fd0-4e36-8382-a9ebbeaf1bea.png">
改为 support 和 power  现在时。
<img width="303" alt="1655095254126" src="https://user-images.githubusercontent.com/97211839/173280929-26febc79-f266-4617-94b7-269149efa130.png">
可以考虑直接Who's 开头 删掉See, 另外底下这段描述没太明白咱们想传达什么
