### ISSUE TITLE
Dashboard for Polkadot Decoded

### ISSUE THREAD

**Issue by Moehringen** [web3go-xyz/web3go.xyz#103]
refer to: https://mb.web3go.xyz/collection/116-polkadot-decoded

Two dashboards are needed for Polkadot decoded presentation: 

1.  Dashboard for Crowdloan: 
Link： https://mb.web3go.xyz/public/dashboard/c3c10928-1d80-4b40-959f-4aa50bea9ece

- [x]             a.  Daily trend Contributors 
- [x]             b.  Daily trend Contributions 
- [x]             c.  Top 10 Contributors with the label. (we already have )
- [x]             d.  Stacked daily trend contributions per  Won project for the first 2 campaigns
- [x]             e.  Total contributors and contributions

3.  Dashboard for XC20 token: 
Link:  https://mb.web3go.xyz/public/dashboard/39cd624b-c4f5-4d52-8a4c-f739fd060c93

On Moonbeam
- [x]         a. XC20 Tokens TVL Daily Trend
- [x]         b. XC20 Tokens TVL Breakdown
- [x]         c.  XC20 Token Locked in Defi contracts    (XC20 Token锁定在哪些dex里)
- [x]         d. XC20 Token  Inflows-Outflows  in Defi contracts  (XC20 Token 在dex里的进出交易量)

**Comment by bianyunjian** [comment]
work on dashboard and finished.  https://mb.web3go.xyz/collection/116-polkadot-decoded
