### ISSUE TITLE
unstake function

### ISSUE THREAD

**Issue by happyJ2024** [web3go-xyz/web3go.xyz#119]
https://www.notion.so/web3builders/Web3Go-Moonbeam-staking-pallet-Unstaking-Scheduled-unstaking-doc-8713a31bf27c4978a284e8991cd69931
unstaking文档

**Comment by imqipan** [comment]
The UI and the interaction design can be viewed at  https://www.figma.com/file/UHdJBdCbMUCDoJ7GdcE9Cr/moombeam?node-id=25%3A8190&t=GIn4sJz0bj43E8jE-0

**Comment by happyJ2024** [comment]
**target_seconds_per_block**  :     apr.utils.js  getBlockTargetSeconds,  default is 12s

 

**blocks_per_round**:   chain constant,   当前页面已有该值roundInfo.length 
![Image](https://user-images.githubusercontent.com/12878885/203500249-544f0105-1721-48c8-a349-5366af1b66d9.png)

**Comment by happyJ2024** [comment]
1. 当执行了api.tx.parachainStaking.scheduleRevokeDelegation(collator) 操作后， 会在链上生成一个schedule记录。
2. 已知当前用户参与的collator列表
3. 通过 api.query.parachainStaking.delegationScheduledRequests(collator) 查找得到 某个 collator下的 schedule记录
结构如下：
```
[
  [
    [
      jcSQcu5RXtWXKPN78zJogNyqsff1j4ffgoJ2njNcDbZ3qNEh5   // collator
    ]
    [
      {
        delegator: jcS3Mpk2s3UdoBTW6QaniZnhn7xbMtfYX7ZZQJGg1DVNcNkk9   //delegator
        whenExecutable: 62,948                                     // 真正能执行确认动作的roundIndex
        action: {
          Revoke: 3,100,000,000,000,000                        // 动作， token数量
        }
      }
    ]
  ]
]
```

4. 匹配当前用户地址和 schedule记录， 如果没有关联， 说明用户没有等待中的revoke操作 
如果有关联， 得到 whenExecutable_roundIndex

5.  已知参数： current_roundIndex, current_blockNumber, whenExecutable_roundIndex， target_seconds_per_block ， blocks_per_round

**est_blocks_v1=    (whenExecutable_roundIndex - current_roundIndex ) * blocks_per_round  **
 
**est_blocks_v2=  est_blocks_v1  -  ( blocks_finished_in_current_round )**   


![Image](https://user-images.githubusercontent.com/12878885/203506696-b61a8c29-8fde-458f-aa59-72eedfd12cd7.png)


**est_seconds =  est_blocks_v2 *  target_seconds_per_block**

**Comment by happyJ2024** [comment]
api.constants. parachainStaking.leaveDelegatorsDelay


![Image](https://user-images.githubusercontent.com/12878885/203726671-adff09c8-b43b-4ff5-b8c1-2ee049554dcf.png)

**Comment by happyJ2024** [comment]
当 whenExecutable_roundIndex <= current_roundIndex ,  此时 execute按钮出现了， 可以执行确认动作

api.tx.xxxx

![Image](https://user-images.githubusercontent.com/12878885/203729124-c73808fc-e604-4899-9310-9a1843ddb0c8.png)

**Comment by happyJ2024** [comment]
取消


![Image](https://user-images.githubusercontent.com/12878885/203729240-02df121d-63b4-47c9-8cdd-e6ae54ec1e77.png)

**Comment by happyJ2024** [comment]
比如：
用户 U，  Collator A,B
U stake 给 A,B  => 显示两条记录，  此时两条都有 revoke按钮
2.   U  revoke A =>  此时 A 显示倒计时，  B 仍然是 revoke按钮
3.   过了一段时间，  U  revoke B =>  此时 A 保持显示倒计时，  B 显示倒计时，  注意AB 倒计时 不同
4.   过了一段时间，A倒计时终结了， 显示 Execute ，  B 仍然显示倒计时
5.   A 执行 Execute ， 完成后A记录应该消失了。
6. B倒计时终结了， 显示 Execute
7.    B 执行 Execute ， 完成后B记录应该消失了。

**Comment by happyJ2024** [comment]
execute 为什么有 delegator参数， 而 cancel 没有这个参数？
execute 可以由别人代为执行
cancel  只能自己执行，默认是针对当前caller

**Comment by imqipan** [comment]
finished and ready to test on the test env.
