### ISSUE TITLE
collator setup for tanganika parachain

### ISSUE THREAD

**Issue by happyJ2024** [web3go-xyz/web3go.xyz#123]
https://parachains.info/details/tanganika

Here is how to become a collator
https://dev.datahighway.com/docs/tutorials/tutorials-nodes-collators-setup#set-up-the-node-as-a-system-service

and here is some documentation on the rewards that can be generated while being a delegator 
https://dev.datahighway.com/docs/getting-started/users-rewards

**Comment by wangminqi** [comment]
https://www.notion.so/web3go/Tanganika-Kusama-347de4fc2b1442a892ee1a8bea673654

**Comment by imqipan** [comment]
I have finished the setup, and it seems that the collator started syncing and there are many files created under the syncing.

**Comment by happyJ2024** [comment]
verify required.

**Comment by happyJ2024** [comment]
enter docker:
```
sudo docker exec -it a91 /bin/bash
```
view log：
```
tail -f /var/log/journal/datahighway.service.log
```

**Comment by happyJ2024** [comment]
![Image](https://user-images.githubusercontent.com/12878885/204957751-65c9c723-1978-4d7c-82da-28221f0e568c.png)

**Comment by happyJ2024** [comment]
sync finished.
we can check it from telemetry site:



![Image](https://user-images.githubusercontent.com/12878885/205530953-ef168d22-a014-44c9-8696-da6375c74aab.png)

**Comment by happyJ2024** [comment]
wait for response from Tanganika team, to give us  access to archive node.

**Comment by imqipan** [comment]
Updated, the indexer service is running! Partial events differentiate from other networks' staking, so impacts/improvements would be further scrutinized.

#### parachainStaking/NewRound
> [Subscan Ref](https://datahighway.subscan.io/block/985097)
> table(RoundInfo) data missing: numberOfCollator, totalBond 

#### <del>mising parachainStaking/CollatorChosen </del>
> table(NominatorActionHistory) data missing

#### <del>mising parachainStaking/CandidateBondedMore </del>
> affected table data:CollatorActionHistory
#### <del>mising parachainStaking/CandidateBondedLess </del>
> affected table data:CollatorActionHistory
#### <del>mising parachainStaking/TotalSelectedSet </del>
> affected table data:CollatorNumberHistory

**Comment by Moehringen** [comment]
@wangminqi hi Minqi, can you take a look at this? there are several events are missed.

**Comment by happyJ2024** [comment]
@wangminqi

**Comment by happyJ2024** [comment]
wait for DHX token from team.
