### ISSUE TITLE
unstake issues

### ISSUE THREAD

**Issue by happyJ2024** [web3go-xyz/web3go.xyz#124]
![Image](https://user-images.githubusercontent.com/12878885/204022411-81d3ea8a-f5f7-4bbf-b1a1-7d053f029687.png)

**Comment by happyJ2024** [comment]
![Image](https://user-images.githubusercontent.com/12878885/204022752-2e58c9e6-6e40-4533-8f03-8666efc5c5d2.png)

**Comment by happyJ2024** [comment]
Est  不建议给出秒， 秒是无法精确显示的，带来误解。

建议是 小时，分钟即可。

**Comment by imqipan** [comment]
fixed

**Comment by oliviaxiting** [comment]
1、弹窗位置没有居中在网页上
2、
<img width="1494" alt="image" src="https://user-images.githubusercontent.com/19482971/204214074-9d20f8cd-b9f4-466a-89a1-724e25017bd2.png">
按钮zhi'j之间间距不对
3.
<img width="280" alt="image" src="https://user-images.githubusercontent.com/19482971/204214184-976d0edd-bed1-4a96-88fe-e8b043adda34.png">

框框内多出一条线

**Comment by imqipan** [comment]
I made huge improvements and issue 3 has been fixed. However, since I could not repeat issues 1 & 2, I can not ensure you it was fixed.
