### ISSUE TITLE
Tips enhancement

### ISSUE THREAD

**Issue by happyJ2024** [web3go-xyz/web3go.xyz#125]
![Image](https://user-images.githubusercontent.com/12878885/204088399-1c0368ba-5816-47a2-aa23-b3f407fe33ea.png)

是否可以增加 tips， 用于说明该功能
1. Revoke：   you can schedule to revoke delegation from current collator
2. Execute:    now you can execute  previous scheduled request to get your tokens back from delegation.
3. Cancel:     you will cancel previous scheduled request and continue with delegation.

**Comment by imqipan** [comment]
Sure, of course. Now the tips were added following the above scenarios and the texts.
