### ISSUE TITLE
Migrate Collators to GCP

### ISSUE THREAD

**Issue by happyJ2024** [web3go-xyz/web3go.xyz#135]
litentry
calamari
MAP Protocol

**Comment by trmaphi** [comment]
Synced to latest blocks
Transfering keys to the new server, and open validator/collator functions

**Comment by happyJ2024** [comment]
need to bind session-key  since ip changed:
litentry
calamari.

**Comment by trmaphi** [comment]
- finished mapprotocol  (mapprotocol only work as daemon)
- calamari statedb seems to corrupt, I'm copying file directly from old node with rsync

**Comment by happyJ2024** [comment]
- [x] copy all files.
- [x] refresh session key if required, pls DM me

**Comment by happyJ2024** [comment]
watching new servers.

**Comment by happyJ2024** [comment]
use Uptime to monit the service
use node_exporter to export mertic data.

**Comment by trmaphi** [comment]
Done Uptime to monit the service

**Comment by happyJ2024** [comment]
Everything has been done.
