### ISSUE TITLE
Data structure on Substrate

### ISSUE THREAD

**Issue by happyJ2024** [web3go-xyz/web3go.xyz#136]
Dashboard:
1. https://analytix.web3go.xyz/layout/dashboardDetail/1f72ec9d-5557-48f9-9d21-2a426b485007
2. https://analytix.web3go.xyz/layout/dashboardDetail/11f029aa-a521-46f2-9ab4-663c1052295f

now all data comes from excel or static data, just provided for internal checking

Target:

1. use On-chain data

**Comment by happyJ2024** [comment]
Manta Atlantic Overview  ==> Calamari   
https://calamari.subscan.io/
https://polkadot.js.org/apps/?rpc=wss%3A%2F%2Fcalamari.systems#/explorer

**Comment by happyJ2024** [comment]
temp repo: 
https://github.com/web3go-xyz/manta-datakit-calamari-indexer

extra doc from Manta team:
https://hackmd.io/o6aaDgBbQF-jx1BVfEjEAA?view

**Comment by happyJ2024** [comment]
temp dev server:
```
Host w3-dev-manta-datakit
    HostName 35.187.244.140
    User ubuntu
    IdentityFile  manta-datakit-private.openssh
```


[manta-datakit-private.zip](https://github.com/web3go-xyz/web3go.xyz/files/12365060/manta-datakit-private.zip)

**Comment by happyJ2024** [comment]
Start with:
1. learn basic raw data: substrate_block_entities,substrate_extrinsic_entities, substrate_event_entities
2. migrate data to  Kafka, Presto, Kudu
3. parse the data with our own bigdata framework

**Comment by zhangqixin9527** [comment]
start developing it for sending the entities to kafka

**Comment by happyJ2024** [comment]
now data has been sent to Kafka successfully.

**Comment by zhangqixin9527** [comment]
I have created tables in Kudu and set up nifi to insert data into tables.

Hope to give me a server to deploy the Calamari Indexer

**Comment by zhangqixin9527** [comment]
The program has been deployed successfully, and the data has been recorded in to Kudu tables.

**Comment by happyJ2024** [comment]
start to fetch blocks after 3M

**Comment by wangminqi** [comment]
https://www.notion.so/web3go/Manta-Substrate-ecdebfcce16d4c46b8c9bf387b3d981e

**Comment by zhangqixin9527** [comment]
try to fix the issue of the calamari-indexer program interruption issue , i found there is throtling on ratelimited endpoint

**Comment by happyJ2024** [comment]
new archive nodes will solve the problem above.

**Comment by happyJ2024** [comment]
fixed, now indexer is ready.

**Comment by zhangqixin9527** [comment]
The program is well but sending Kafka messages from calamari-indexer fails. 
I’m attempting to adjust the Kafka producer parameters and will continue monitoring the program.

Currently, the program is sending messages to Kafka, but the processing speed is very slow.
