### ISSUE TITLE
TGM - Number of transactions on chain

### ISSUE THREAD

**Issue by Shihao66** [web3go-xyz/web3go.xyz#40]
Token god mode - Chain perspective:

Task 1:
Get familiar with Metabase and use it to show the number of transactions happened on chain

**Comment by ljl1314** [comment]
For more details, refer to
https://www.notion.so/litentry/Token-god-mode-features-bc9781a317e944d697615cc831cb0418#a987068b216140d59a3cc47409ee47e9

**Comment by ljl1314** [comment]
what types of transactions should be considered? The <transfer> transaction includes both of the columns account_from and account_to, for <withdraw> and <deposit> only one account related, what logic would it be like to calculate the result?

**Comment by ljl1314** [comment]
the dashboard-0 is updated in Metabase to add the analysis figures for the entire blockchain, not sure the figures reflect correctly or not
