### ISSUE TITLE
MoonPush: read token contract address from chain for asset across bridge

### ISSUE THREAD

**Issue by bianyunjian** [web3go-xyz/web3go.xyz#70]
for moonriver: 
- [ ] support asset across bridge:  Anyswap, Celer
- [ ] read token contract address
- [ ] read token symbol, decimals

**Comment by bianyunjian** [comment]
**concept:** 
chain 
address
token
contract address 
contract method topic

**Comment by bianyunjian** [comment]
tools:
web3.js
ether.js
polkadot.js

**Comment by bianyunjian** [comment]
explorer: 
https://moonbeam.moonscan.io/
https://moonbeam.subscan.io/
https://polkadot.js.org/apps/?rpc=wss%3A%2F%2Fmoonbeam.api.onfinality.io%2Fpublic-ws#/explorer/query/1001624

**Comment by ahern2018** [comment]
1. Regularly pull contract information from anyswap, and extract the token according to chainId/srcChainId = 1284(Moonbeam)/1285(Moonriver);
2. Use ethers.js to query token information.
3. Normalize data and insert into database.
