### ISSUE TITLE
MoonID UI develop

### ISSUE THREAD

**Issue by bianyunjian** [web3go-xyz/web3go.xyz#73]
api: http://16.163.5.216:8082/api/

**Comment by oliviaxiting** [comment]
![image](https://user-images.githubusercontent.com/19482971/167278917-c704f737-3b2b-41a1-be00-3ab8f8456429.png)
黑色文字是regular

**Comment by oliviaxiting** [comment]
![image](https://user-images.githubusercontent.com/19482971/167278951-7c69fecb-4c9e-4969-a76d-a8c1e5d450b6.png)
banner的位置偏外面设计稿是比较聚拢看着会比较小，搜索框内的文字也是细体

**Comment by oliviaxiting** [comment]
![image](https://user-images.githubusercontent.com/19482971/167279097-18d50737-cb6c-4ff7-8e6b-985fa0864692.png)
icon有点偏上

**Comment by oliviaxiting** [comment]
![image](https://user-images.githubusercontent.com/19482971/167279147-5808c77d-0f22-4a49-94e7-2f3c458ac0c0.png)
这个头像能放放在那个圆里面

**Comment by oliviaxiting** [comment]
![image](https://user-images.githubusercontent.com/19482971/167279162-d973fd7d-a5f3-4e1a-b2d2-999b2707d6eb.png)
切换的按钮逻辑是第一屏，向左的那个置灰无法点击，右边的那个高亮表示可点击，最后一屏右边的那个按钮置灰。第一屏时，第一名处于选中状态
![image](https://user-images.githubusercontent.com/19482971/167279200-da7cb9d6-9347-460d-90b0-0ec4c7cf829e.png)

**Comment by oliviaxiting** [comment]
![image](https://user-images.githubusercontent.com/19482971/167279208-0f437a9a-c8b2-4e95-b0d6-d8edbbb0b98e.png)
hover没有阴影

**Comment by oliviaxiting** [comment]
![image](https://user-images.githubusercontent.com/19482971/167279220-01296e3a-848d-4a7f-a61e-278eeea16a50.png)
底部距离太高，缩减到1/2

**Comment by oliviaxiting** [comment]
![image](https://user-images.githubusercontent.com/19482971/167279258-db3e5998-0859-4da4-a309-e6682ab895d8.png)
不需要外面的那个白框

**Comment by LeonITMCuiP** [comment]
![image](https://user-images.githubusercontent.com/97211839/167370273-82b0df6b-8b11-41cf-bf75-79025981c705.png)
点这个 放大镜没法激活搜索。

**Comment by LeonITMCuiP** [comment]
<img width="748" alt="1652084854(1)" src="https://user-images.githubusercontent.com/97211839/167370828-2e9b12cc-f165-43e1-ac64-d9c1fdc69e13.png">
中间的这两个钱包的样式可以考虑做的更胖更大一点，夸张一点好看 （非必要）

**Comment by LeonITMCuiP** [comment]
选择连钱包的时候，钱包跳出来后，显示xxxx网站尝试与你链接，需要sign。 这个地方的大logo是web3go，现阶段可以换成moodID的logo
<img width="93" alt="1652085432(1)" src="https://user-images.githubusercontent.com/97211839/167372593-a20704d4-407a-4417-a64f-166c1733cdd9.png">
另外链接成功，和断开链接的时候，上面跳出来的是 connect success  和 discoonect success.   这两处可以直接使用  connected  和 disconnected  字可以比现在大一点

**Comment by LeonITMCuiP** [comment]
<img width="809" alt="1652105599(1)" src="https://user-images.githubusercontent.com/97211839/167429164-42e1954b-efdd-436b-abf4-b866236b810a.png">
这里有几个建议：1， 我们的卡片上用户的名字（截图上显示的是一个地址但用户也有的有名字），以及下面的total score 搞成居中是不是比左对齐看着舒服一些？
2， 我建议treasure vitality artististic 三角形角上的三个词，用粗体可以稍微大一点，实际浏览网页时候不仔细看看不到这三个词，注意不到。

**Comment by LeonITMCuiP** [comment]
<img width="395" alt="1652106197(1)" src="https://user-images.githubusercontent.com/97211839/167431234-898a92da-41e5-4968-98a3-2e5c1db6b2ab.png">
标题把points 删掉， 只写Calculation Instructions 就行。 
另外那四列有的左对齐有的中间对齐，我建议直接全部居中对齐
<img width="499" alt="1652106394(1)" src="https://user-images.githubusercontent.com/97211839/167432076-cda8663d-8a16-49b6-a210-ff81a84ba183.png">
zhe这个红框的也改一下。

**Comment by LeonITMCuiP** [comment]
<img width="228" alt="1652106674(1)" src="https://user-images.githubusercontent.com/97211839/167432960-f942074c-d485-4fab-b53a-3474d6d5264a.png">

**Comment by oliviaxiting** [comment]
> 
现在设计字体变小了居中就会变得很奇怪

**Comment by oliviaxiting** [comment]
![image](https://user-images.githubusercontent.com/19482971/167558560-9321f70a-b41f-4870-a325-8513ed88dc19.png)
进度条出了bug

**Comment by LeonITMCuiP** [comment]
<img width="677" alt="520f0dbda814c9decccdf4165848a41" src="https://user-images.githubusercontent.com/97211839/168026494-819151a3-9713-40fe-ab97-12a84ecb296e.png">
鼠标热区扩大到整个红框范围，且鼠标放到红框范围的时候，跟下面的一样，view details要出现。

**Comment by zhanggoodzhi** [comment]
fixed

**Comment by LeonITMCuiP** [comment]
<img width="648" alt="1653535707(1)" src="https://user-images.githubusercontent.com/97211839/170410093-77e5bcbf-ae25-4b1a-8e70-339223473203.png">
![1653535849(1)](https://user-images.githubusercontent.com/97211839/170410353-9e445ad2-c8a9-45e7-9ba3-a8c267dc6f7a.jpg)
这两处的单词都需要改成artisticity

**Comment by LeonITMCuiP** [comment]
![1653536659](https://user-images.githubusercontent.com/97211839/170411781-fc5bd38f-5ac8-48f9-8146-106ffe949b8e.jpg)

**Comment by zhanggoodzhi** [comment]
fixed
