### ISSUE TITLE
UI Adjustments for MoonID

### ISSUE THREAD

**Issue by SeniorPumpkin** [web3go-xyz/web3go.xyz#75]
Artistic —> Artisticity
![Treasure](https://user-images.githubusercontent.com/79832732/167434943-31b1fdd1-9bce-41d0-b852-9f5273216074.png)

Score of Balance -> Treasure Score
Item -> Type
Balance: Wallet Balance
Points Calculation Instructions -> Score Calculation Instruction
![Treasure](https://user-images.githubusercontent.com/79832732/167434986-ccbae5a6-7335-4d0d-9dd6-d4ac28fab707.png)

Score of Transaction: Vitality Score
Item -> Type
Number of Transactions(DEX) -> Number of Transactions (DEX)  [Space before parentheses]
Number of Transactions(except DEX) -> Number of Transactions (non-DEX)
![Vitality](https://user-images.githubusercontent.com/79832732/167435031-ce1dcc7f-7c4b-45dd-b4f4-5a2670dc652b.png)

Rule -> Value
Score Items -> Type
Balance -> Wallet Balance
Metal -> Badges for a Metal status
![Treasure](https://user-images.githubusercontent.com/79832732/167435078-0b6ac565-48fe-4f3a-a5ac-203c56e7053b.png)

**Comment by bianyunjian** [comment]
update the description of items

**Comment by zhanggoodzhi** [comment]
fixed
