### ISSUE TITLE
Moonbeam Runtime upgrade to 1601 with breakchange

### ISSUE THREAD

**Issue by bianyunjian** [web3go-xyz/web3go.xyz#92]
最新的运行时1601更新里面有一个变动你们可能需要留意一下：
Treasury deposit events
With the better support for Ethereum priority fees, there can be 2 treasury.Deposit substrate event per transaction (one corresponding to 20% of the gas used, and one corresponding to 20% of the priority fees being consumed)

**Comment by wangminqi** [comment]
yes. Noticed
