### ISSUE TITLE
Moonbeam Dashboard: outward - XC20 to other parachain

### ISSUE THREAD

**Issue by bianyunjian** [web3go-xyz/web3go.xyz#96]
XC20
Only partly possible. Each archive node can only monitor its own native xc20 and all xc20 tokens inside its ecosystem. We are building the indexer for relay-chain(Kusama), then we can know where the XC20-KSM goes.

**Comment by trmaphi** [comment]
Can't performance analysis that without tracking other parachains tokens pallet. So, the conclusion is not worth the effort.

**Comment by trmaphi** [comment]
Technically speaking, there're 10 steps to monitor each transfer https://www.notion.so/litentry/Test-c60f0ee5309640ba9a35b0fcdbfaca2a

**Comment by trmaphi** [comment]
There're two layers get into consideration when the token from EVM enable para chain like Astra and Acala

- EVM
- Substrate

They have their own method of mapping EVM -> substrate asset pallet -> wrap them as XCM message.

The standard of each chain can be found at:

https://github.com/paritytech/substrate-open-working-groups/blob/main/SOWG/1-polkadot-token-standard.md
