### ISSUE TITLE
Moonbeam Dashbord: Contract creates and creators(Unique address)

### ISSUE THREAD

**Issue by bianyunjian** [web3go-xyz/web3go.xyz#98]
Code Repo:
https://github.com/web3go-xyz/moonbeam-data-kit/tree/main/offchain-processor/substrate-layer-offchain-processor

Contracts created.  
- [x] The number of contracts created.  
- [x] daily created contracts
- [x] Contracts unique creator(developer).

**Comment by bianyunjian** [comment]
slow performance issue for code:
![image](https://user-images.githubusercontent.com/12878885/173596615-48afc336-7f0a-4f58-b83e-a6355fed9114.png)
![image](https://user-images.githubusercontent.com/12878885/173596628-128d72bc-c583-4127-9d08-81727d1c317c.png)

**Comment by lbj2016** [comment]
Fixed
